### PR TITLE
Add Takashima Momoka holding open programming book with diagrams

### PR DESCRIPTION
**Pull request by trigger-segfault**
Source Manga: SE (System Engineer)

### CODE REVIEW

**Comment by pjpollina** [comment]
Not totally sure if these two qualify, told Null to take a look at them.

**Comment by trigger-segfault** [comment]
Yeah understandable, also why I submitted each separately for a case-by-case basis.

**Comment by Asday** [comment]
#77 for sure does I reckon.  This one's questionable.

**Comment by boyEstrogen** [comment]
The book in this one isn't super clear that its about programming. I'd like to try and avoid adding images that aren't obviously about programming.

**Pull request closed without merging**
