### PR TITLE
Add Miss Monochrome holding the C Programming Language

### PR DESCRIPTION
**Pull request by bucket3432**

### CODE REVIEW

**Comment by Asday** [comment]
Did you make this?  It would be cool if you gave it a bit of yellow light to match the surroundings if so.

The higher-effort the shitposting, the better.

**Comment by bucket3432** [comment]
Yes, this one's mine. I already did some white-balancing and figured the white of the book is a purer white than Monochrome's outfit, but I'll see if I can tweak it a little more.

**Comment by bucket3432** [comment]
@Asday How's that? I used a sample point closer to the book and used two overlaid layers instead of one.

**Comment by boyEstrogen** [comment]
thats that good shit merged

**Comment by Asday** [comment]
Looks beaut, dude.  @bucket3432

**Pull request merged**
